server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

spring:
  application:
    name: thai-auto-insurance-backend
  
  profiles:
    active: dev
  
  datasource:
    url: jdbc:h2:mem:thai_insurance;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  h2:
    console:
      enabled: true
      path: /h2-console
      
  sql:
    init:
      mode: always
      continue-on-error: false
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Bangkok
  
  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  jackson:
    time-zone: Asia/Bangkok
    date-format: yyyy-MM-dd HH:mm:ss
    property-naming-strategy: SNAKE_CASE
  
  security:
    require-ssl: false

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:MyVeryLongSecretKeyForHS512Algorithm12345678901234567890123456789012345678901234567890}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days in milliseconds

# Thai Locale Configuration
thai:
  locale:
    country: TH
    language: th
    timezone: Asia/Bangkok
    currency: THB

# Logging Configuration
logging:
  level:
    com.thaiinsurance.autoinsurance: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/thai-auto-insurance.log

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
  info:
    env:
      enabled: true

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  info:
    title: Thai Auto Insurance API
    description: REST API for Thai Auto Insurance Management System
    version: 1.0.0