spring:
  datasource:
    url: jdbc:h2:mem:thai_auto_insurance_dev;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  security:
    require-ssl: false

# Development specific configurations
logging:
  level:
    com.thaiinsurance.autoinsurance: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

# CORS Configuration for development
cors:
  allowed-origins: http://localhost:4200,http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600