# Test configuration for Thai Auto Insurance Backend
spring:
  application:
    name: thai-auto-insurance-test
    
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        
  flyway:
    enabled: false
    
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: test-secret-key-for-testing-purposes-only-minimum-32-characters-required
          
  test:
    database:
      replace: none

# JWT Configuration for testing
jwt:
  secret: dGVzdC1zZWNyZXQta2V5LWZvci10ZXN0aW5nLXB1cnBvc2VzLW9ubHktbWluaW11bS0zMi1jaGFyYWN0ZXJzLXJlcXVpcmVk
  expiration: 3600000 # 1 hour for testing
  
# Logging configuration
logging:
  level:
    com.thaiinsurance.autoinsurance: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG
    org.springframework.test: DEBUG
    
# TestContainers configuration
testcontainers:
  postgresql:
    image: postgres:15-alpine
    database: thai_insurance_test
    username: test_user
    password: test_password
    
# Thai specific test configurations
thai:
  validation:
    strict-mode: true
  test-data:
    generate-realistic: true
    
# Actuator for test monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always